server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: / # Fixed from server.context-path

spring:
  application:
    name: tr-monitor-service
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:DnictPro@123}
  boot:
    admin:
      context-path: /
      ui:
        title: 'APP MANAGEMENT SYSTEM ADMIN'
        brand: '<img src="assets/img/icon spring-boot-admin.svg"><span>Spring App Management System </span>'
        available-languages:
          - en
        view-settings:
          - name: 'about'
            enabled: false
      notify:
        mail:
          enabled: false # Avoid SMTP issues
          to: ${NOTIFY_MAIL_TO:tyran8x@gmail.com}
          from: ${NOTIFY_MAIL_FROM:MCDT app management system admin <noreply>}
        telegram:
          enabled: true
          chat-id: ${TELEGRAM_CHAT_ID:-1003054884531}
          auth-token: ${TELEGRAM_AUTH_TOKEN:8423245923:AAFHSTIpl6A5vsbkRbYDMqkPw73t5PKP34E}
          parse-mode: HTML
          disable-notify: false

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

telegram:
  bot:
    token: "8423245923:AAFHSTIpl6A5vsbkRbYDMqkPw73t5PKP34E"
    chat-id: "1001217744693"
    username: "@TrSBABot"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false # Avoid Gmail rate limit

logging:
  level:
    vn.tr: ${LOGGING_LEVEL_VN_TR:INFO}
    org.springframework: ${LOGGING_LEVEL_SPRINGFRAMEWORK:WARN}
  config: classpath:logback-spring.xml
  file:
    name: ${LOG_PATH:/opt/logs}/${spring.application.name:tr-monitor-service}/sys-info.log
