server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: / # Fixed from server.context-path

spring:
  application:
    name: tr-monitor-service
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:DnictPro@123}
  boot:
    admin:
      context-path: /
      ui:
        title: 'MCDT APP MANAGEMENT SYSTEM ADMIN'
        brand: '<img src="assets/img/icon spring-boot-admin.svg"><span>Spring App Management System </span>'
        available-languages:
          - en
        view-settings:
          - name: 'about'
            enabled: false
      notify:
        mail:
          enabled: false # Avoid SMTP issues
          to: ${NOTIFY_MAIL_TO:tyran8x@gmail.com}
          from: ${NOTIFY_MAIL_FROM:MCDT app management system admin <noreply>}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false # Avoid Gmail rate limit

logging:
  level:
    vn.tr: ${LOGGING_LEVEL:INFO}
    org.springframework: warn
  config: classpath:logback.xml
