server:
  port: ${SERVER_PORT:9090}
  servlet:
    context-path: /

spring:
  config:
    import:
      - "optional:configserver:${CONFIG_SERVER_URL:http://mcdt-config:8888}"
  cloud:
    config:
      uri: http://mcdt-config:8888
      username: ${CONFIG_SERVER_USERNAME:-huydq}
      password: ${CONFIG_SERVER_PASSWORD:-abc@123}
  boot:
    admin:
      context-path: /
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://mcdt-eureka:8061/eureka/}
